fix(GraphQL): RHICOMPL-3244 make tags a named scope for systems
RedHatInsights/compliance-backend pull request #1438
Opened 2022-08-24 08:07 UTC by skateman

Should fix the problem of non-scoped tags, depends on https://github.com/RedHatInsights/compliance-backend/pull/1437

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

2022-08-24 11:48 UTC, romanblanco approved these changes
LGTM :+1:

2022-09-08 05:36 UTC, skateman commented
@vkrizan wdyt about this one? We're storing a scope from before applying the tagging in order to list all available tags later.

2022-09-09 08:49 UTC, vkrizan requested changes

2022-09-09 08:49 UTC, vkrizan commented on app/graphql/resolvers/concerns/collection.rb
> +        context[:wide_scope] = yield
Looks like the filters are not stored, so why not just store the `base_scope`? What am I missing?

This implementation seems very rigid. Can you think of a simplified one that can be better understandable?

2022-09-09 09:53 UTC, vkrizan approved these changes
Now we're talking. :+1:

2022-09-09 10:35 UTC, merged