refactor(RBAC): RHICOMPL-3690 configure rbac without url splitting
RedHatInsights/compliance-backend pull request #1625
Opened 2023-04-20 09:40 UTC by RoamingNoMaD

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

2023-04-20 09:41 UTC, skateman commented on config/initializers/0_clowder-config.rb
> +      scheme: "#{rbac_scheme}"
```suggestion
      scheme: rbac_scheme
```

2023-04-20 09:42 UTC, skateman commented on config/initializers/0_clowder-config.rb
> +  rbac_hostname = rbac_config.hostname
Let's name it `rbac_host` for consistency. And maybe move the port into this variable as well. See below the reasoning.

2023-04-21 07:45 UTC, skateman approved these changes
![The Seal of Approval](http://www.skateman.eu/seal.jpg)

2023-04-21 07:50 UTC, romanblanco requested changes
@RoamingNoMaD `development.yml` and `production.yml` also need an update

2023-04-21 07:57 UTC, skateman commented
> @RoamingNoMaD `development.yml` and `production.yml` also need an update

Not really, those use clowder and these values aren't even consumed at all. Eventually in the next ticket we will drop the test.yml as well, at least the clowder-related values by clowderizing the test environment. So no further changes are needed for now.

2023-04-21 08:51 UTC, romanblanco approved these changes

2023-04-21 08:52 UTC, merged