feat(APIv2): RHICOMPL-3956 align offset with standard expectations
RedHatInsights/compliance-backend pull request #1810
Opened 2023-09-01 12:04 UTC by RoamingNoMaD

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

2023-09-02 09:30 UTC, skateman requested changes
The V1 implementation wrongly uses the term offset, where it is actually representing page number. Offset means how many items are skipped from the beginning of the set when displaying the result, so the relationship between these two is `offset = (page_number - 1) * per_page`. The code should be adjusted accordingly...

2023-09-02 09:30 UTC, skateman commented on app/controllers/concerns/v2/metadata.rb
> +            relationships: relationships_enabled?
This field can be removed, we won't use it in V2, at least not in its current form

2023-09-02 09:30 UTC, skateman commented on app/controllers/concerns/v2/metadata.rb
> +          relationships: relationships_enabled?
Same here...

2023-09-02 09:30 UTC, skateman commented on app/controllers/concerns/v2/pagination.rb
> +        permitted_params[:offset] || 1
This has to be 0 by default.

2023-09-04 14:48 UTC, skateman commented on app/controllers/concerns/v2/pagination.rb
> +        pagination_offset + 1
This is definitely not good, the relationship between offset and page should be a multiplication of the page number with the per_page limit.

2023-09-05 13:22 UTC, skateman commented
Something is off:
```
$ curl -k -H "Content-Type: application/json" -H "X-RH-IDENTITY: $RHI" -XGET "http://localhost:3000/api/compliance/v2/security_guides?limit=2" | jq '.data[].id'
"02ee36bf-d662-464c-938a-7ab025cf9db6"
"12cbb019-e776-4334-89ef-612b18c412c3"

$ curl -k -H "Content-Type: application/json" -H "X-RH-IDENTITY: $RHI" -XGET "http://localhost:3000/api/compliance/v2/security_guides?limit=2&offset=1" | jq '.data[].id'
"02ee36bf-d662-464c-938a-7ab025cf9db6"
"12cbb019-e776-4334-89ef-612b18c412c3"

$ curl -k -H "Content-Type: application/json" -H "X-RH-IDENTITY: $RHI" -XGET "http://localhost:3000/api/compliance/v2/security_guides?limit=2&offset=2" | jq '.data[].id'
"3a5db8e7-8ff2-41d9-a597-81dc762a760e"
"3fd0dbe6-7ad7-49c5-933e-0ff877890c15"

$ curl -k -H "Content-Type: application/json" -H "X-RH-IDENTITY: $RHI" -XGET "http://localhost:3000/api/compliance/v2/security_guides?limit=2&offset=3" | jq '.data[].id'
"3a5db8e7-8ff2-41d9-a597-81dc762a760e"
"3fd0dbe6-7ad7-49c5-933e-0ff877890c15"

curl -k -H "Content-Type: application/json" -H "X-RH-IDENTITY: $RHI" -XGET "http://localhost:3000/api/compliance/v2/security_guides?limit=2&offset=4" | jq '.data[].id'
"464e02d0-0220-4c8a-9371-2d821585f4eb"
"50cbb6ab-27ca-4393-9b08-eaecca41d657"
```

2023-09-05 15:08 UTC, RoamingNoMaD commented
> Something is off:
> 
> ```
> $ curl -k -H "Content-Type: application/json" -H "X-RH-IDENTITY: $RHI" -XGET "http://localhost:3000/api/compliance/v2/security_guides?limit=2" | jq '.data[].id'
> "02ee36bf-d662-464c-938a-7ab025cf9db6"
> "12cbb019-e776-4334-89ef-612b18c412c3"
> 
> $ curl -k -H "Content-Type: application/json" -H "X-RH-IDENTITY: $RHI" -XGET "http://localhost:3000/api/compliance/v2/security_guides?limit=2&offset=1" | jq '.data[].id'
> "02ee36bf-d662-464c-938a-7ab025cf9db6"
> "12cbb019-e776-4334-89ef-612b18c412c3"
> 
> $ curl -k -H "Content-Type: application/json" -H "X-RH-IDENTITY: $RHI" -XGET "http://localhost:3000/api/compliance/v2/security_guides?limit=2&offset=2" | jq '.data[].id'
> "3a5db8e7-8ff2-41d9-a597-81dc762a760e"
> "3fd0dbe6-7ad7-49c5-933e-0ff877890c15"
> 
> $ curl -k -H "Content-Type: application/json" -H "X-RH-IDENTITY: $RHI" -XGET "http://localhost:3000/api/compliance/v2/security_guides?limit=2&offset=3" | jq '.data[].id'
> "3a5db8e7-8ff2-41d9-a597-81dc762a760e"
> "3fd0dbe6-7ad7-49c5-933e-0ff877890c15"
> 
> $ curl -k -H "Content-Type: application/json" -H "X-RH-IDENTITY: $RHI" -XGET "http://localhost:3000/api/compliance/v2/security_guides?limit=2&offset=4" | jq '.data[].id'
> "464e02d0-0220-4c8a-9371-2d821585f4eb"
> "50cbb6ab-27ca-4393-9b08-eaecca41d657"
> ```

2023-09-06 18:05 UTC, skateman commented
Coverage issues seem relevant...

2023-09-13 15:23 UTC, skateman commented on spec/controllers/v2/concerns/with_metadata_spec.rb
> -  let(:meta_keys) { %w[total limit offset relationships] }
I agree, please at least move it to a separate commit.

2023-09-14 07:14 UTC, romanblanco commented on app/controllers/concerns/v2/metadata.rb
> +  # Sets up the metadata to be passed fo fast_jsonapi to be
```suggestion
  # Sets up the metadata to be passed to fast_jsonapi to be
```

2023-09-14 07:52 UTC, romanblanco approved these changes
I have tested the PR and I'm receiving an expected outputs.

LGTM :+1:

2023-09-14 07:54 UTC, skateman approved these changes
![The Seal of Approval](http://www.skateman.eu/seal.jpg)

2023-09-14 07:54 UTC, merged