fix(APIv2): RHINENG-2097 allow profiles and rules to be indexed by ref_id
RedHatInsights/compliance-backend pull request #1878
Opened 2023-11-21 14:45 UTC by RoamingNoMaD

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

2023-11-23 17:07 UTC, skateman commented on app/controllers/v2/profiles_controller.rb
> +      @profile ||= if ::UUID.validate(permitted_params[:id])
I would put this logic into the concern as it is repetitive in more than one controller.

2023-11-23 17:08 UTC, skateman commented on app/controllers/v2/rules_controller.rb
> +    include Referring
```suggestion
    include IndexableByRefId
```

2023-11-23 17:15 UTC, skateman commented on spec/controllers/v2/concerns/rendering_spec.rb
> +  context 'referrable resource', if: [V2::ProfilesController, V2::RulesController].include?(described_class) do
This logic is the opposite of declarative, instead please create a new file called `indexable_by_ref_id_spec.rb` under the concerns and define a shared example there that you explicitly specify.

2023-11-24 10:14 UTC, RoamingNoMaD commented
/retest

2023-11-24 10:54 UTC, skateman requested changes

2023-11-24 10:54 UTC, skateman commented on spec/controllers/v2/profiles_controller_spec.rb
> +    it_behaves_like 'indexable by ref id', :security_guide
```suggestion
    it_behaves_like 'indexable by ref_id', :security_guide
```

2023-11-24 10:54 UTC, skateman commented on app/controllers/concerns/v2/indexable_by_ref_id.rb
> +      def referize(id)
```suggestion
      def to_ref_id(id)
```

2023-11-24 10:54 UTC, skateman commented on app/controllers/concerns/v2/indexable_by_ref_id.rb
> +      def find_by_id_or_ref_id(scope, id)
```suggestion
      def ref_id_lookup(scope, id)
```

2023-11-24 11:08 UTC, romanblanco commented
Failing QE test does not seem to be relevant:

```
10:38:44 [2023-11-24T10:38:44.553Z] ==================================== ERRORS ====================================
10:38:44 [2023-11-24T10:38:44.553Z] ___________ ERROR at teardown of test_graphql_host_groups_filtering ____________
10:38:44 [2023-11-24T10:38:44.553Z] 
10:38:44 [2023-11-24T10:38:44.553Z]     @request.addfinalizer
10:38:44 [2023-11-24T10:38:44.553Z]     def _finalizer():
10:38:44 [2023-11-24T10:38:44.553Z] >       second_system.delete()
10:38:44 [2023-11-24T10:38:44.553Z] 
10:38:44 [2023-11-24T10:38:44.553Z] /iqe_venv/lib/python3.9/site-packages/iqe_compliance/tests/test_graphql.py:1063:
```

2023-11-24 11:09 UTC, romanblanco approved these changes
LGTM :+1:

2023-11-24 13:18 UTC, skateman approved these changes
![The Seal of Approval](http://www.skateman.eu/seal.jpg)

2023-11-24 13:18 UTC, merged