feat(APIv2): RHINENG-11773 filter failed rules by severity
RedHatInsights/compliance-backend pull request #2190
Opened 2024-08-26 12:16 UTC by romanblanco

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

2024-08-26 12:27 UTC, skateman requested changes
We can get to something like this:
```suggestion
        :additional_rule_results:
          - severity: 'high'
             result: 'pass'
          - severity: 'high'
             result: 'fail'
          - severity: 'low'
             result: 'fail'
```

2024-08-26 12:27 UTC, skateman commented on spec/controllers/v2/test_results_controller_spec.rb
> +            Faker::Internet.uuid => [level, 'fail']
AFAIK you don't need the left side, so you can get rid of these objects completely. SImply define everything in the YAML.

2024-08-26 12:44 UTC, romanblanco commented on app/models/v2/test_result.rb
> +      values = val.split(',').map(&:strip)
We do need to separate the values here.

2024-08-26 13:00 UTC, skateman commented on app/models/v2/test_result.rb
> +      values = val.split(',').map(&:strip)
Yes, but do we need a `,` or isn't space enough? The rule of thumb is if there's space in the strings that you're searching for (see other examples).

2024-08-26 13:05 UTC, romanblanco commented on app/models/v2/test_result.rb
> +      values = val.split(',').map(&:strip)
There is no space in the string to split by.

2024-08-26 13:53 UTC, skateman commented on app/models/v2/test_result.rb
> +      { conditions: "v2_test_results.id IN (#{ids.to_sql})" }
I know why you're bumping into the select cache: you don't need to select from the test results table at all. You can directly go to rule_results and join it with rules + select by `test_result_id`. That way you're joining one less table and you won't need the `reselect`

2024-08-26 13:54 UTC, skateman commented on spec/fixtures/files/searchable/test_results_controller.yaml
> +            result: 'fail'
Please add more than just a single rule result here + combine them with passing tests with higher severity to properly cover the DB lookup.

2024-08-26 13:58 UTC, skateman commented on app/models/v2/test_result.rb
> +    searchable_by :failed_rule_severity, %i[in] do |_key, _op, val|
If you do `in` then you'd also have to do `eq` for semantic compatibility.

2024-08-26 18:20 UTC, romanblanco commented
/retest

2024-08-27 04:36 UTC, skateman requested changes
One minor issue.

2024-08-27 04:36 UTC, skateman commented on app/models/v2/test_result.rb
> +      values = ['IN'].include?(op) ? val.split : val
You don't need to deal with the operator at all, the `split` returns a single element array when no separator is detected. So you can always call `split`, see other existing examples.

2024-08-27 07:43 UTC, skateman reviewed
One last thing as you need to rebase anyway

2024-08-27 07:43 UTC, skateman commented on spec/fixtures/files/searchable/test_results_controller.yaml
> +            result: 'pass'
Nit: use symbols

2024-08-27 07:43 UTC, skateman commented on spec/factories/test_result.rb
> +          result: rr['result']
Nit: use symbols

2024-08-27 08:44 UTC, skateman approved these changes
![The Seal of Approval](http://www.skateman.eu/seal.jpg)

2024-08-27 09:07 UTC, merged