[RHICOMPL-904] Move InventoryHostNotFound back to HostInventoryAPI
RedHatInsights/compliance-backend pull request #573
Opened 2020-09-11 20:07 UTC by akofink

This was not caught by our tests because Xccdf::Hosts was referenced and loaded. You can check it in the console:

```rb
# Before
[1] pry(main)> InventoryHostNotFound
NameError: uninitialized constant InventoryHostNotFound
from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `block in load_missing_constant'
Caused by NameError: uninitialized constant InventoryHostNotFound
from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant'
[2] pry(main)> Xccdf::Hosts
=> Xccdf::Hosts
[3] pry(main)> InventoryHostNotFound
=> InventoryHostNotFound

# After
[1] pry(main)> InventoryHostNotFound
NameError: uninitialized constant InventoryHostNotFound
from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `block in load_missing_constant'
Caused by NameError: uninitialized constant InventoryHostNotFound
from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant'
[2] pry(main)> HostInventoryAPI
=> HostInventoryAPI
[3] pry(main)> InventoryHostNotFound
=> InventoryHostNotFound
```

I'm not sure why it got moved; it may have been a mistake. `InventoryHostNotFound` definitely makes the most sense on `HostInventoryAPI`.

Signed-off-by: Andrew Kofink <akofink@redhat.com>

2020-09-14 08:00 UTC, vkrizan requested changes
Shouldn't the `InventoryHostNotFound` class be (almost) always preloaded (accessible) to the top level.
It is supposed to be caught in
* [ParseReportJob](app/jobs/parse_report_job.rb)
* [sync_with_inventory.rake](lib/tasks/sync_with_inventory.rake)

```
class ParseReportJob
  def self.testme
    raise ::InventoryHostNotFound
  end
end
```
```
> ParseReportJob.testme
NameError: uninitialized constant InventoryHostNotFound
```
Am I forgetting something?

2020-09-14 12:42 UTC, akofink commented
The only place we `raise InventoryHostNotFound` is within the `HostInventoryAPI`, and that's why it should live there. Any class that expects this exception in a rescue is using the `HostInventoryAPI` which will ensure the error class is loaded. If it were designed to be raised elsewhere, then it should live in its own class file so Rails can find and load it properly.

2020-09-15 09:00 UTC, vkrizan approved these changes

2020-09-15 12:47 UTC, akofink commented
Thanks for the review!

2020-09-15 12:47 UTC, merged